import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';
import { Button } from '../components/common/Button';

export const TermsOfService: React.FC = () => {
  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="mb-6">
          <Link to="/">
            <Button variant="secondary" className="flex items-center space-x-2">
              <ArrowLeft className="w-4 h-4" />
              <span>Back to Home</span>
            </Button>
          </Link>
        </div>

        <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-8">
          <h1 className="text-4xl font-bold text-gray-900 mb-2">Terms of Service</h1>
          <p className="text-gray-600 mb-8">Last updated: {new Date().toLocaleDateString()}</p>

          <div className="prose prose-gray max-w-none space-y-6">
            <section>
              <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">1. Acceptance of Terms</h2>
              <p className="text-gray-700 leading-relaxed">
                By accessing and using RepoResume.ai ("the Service"), you accept and agree to be bound by the terms 
                and provision of this agreement. If you do not agree to abide by the above, please do not use this service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">2. Description of Service</h2>
              <p className="text-gray-700 leading-relaxed">
                RepoResume.ai is a web application that uses artificial intelligence to generate personalized resumes 
                and cover letters by analyzing your GitHub repositories and matching them to job descriptions. The 
                Service uses OpenAI's GPT-4o API to generate content and requires GitHub OAuth authentication to 
                access your repositories.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">3. User Accounts and Authentication</h2>
              <p className="text-gray-700 leading-relaxed">
                To use the Service, you must authenticate using GitHub OAuth. By authenticating, you grant us 
                permission to access your GitHub repositories for the purpose of analyzing your projects and 
                generating resume content. You are responsible for maintaining the security of your account and 
                for all activities that occur under your account.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">4. Free Tier and Usage Limits</h2>
              <p className="text-gray-700 leading-relaxed mb-3">
                The Service provides a free tier with the following limitations:
              </p>
              <ul className="list-disc pl-6 text-gray-700 space-y-2">
                <li>10 free resume and cover letter generations per month</li>
                <li>Generation count automatically resets at the beginning of each month</li>
                <li>Unused generations do not roll over to the next month</li>
              </ul>
              <p className="text-gray-700 leading-relaxed mt-4">
                We reserve the right to modify these limits at any time. We will provide reasonable notice of any 
                changes to the free tier limits.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">5. User Content and Data</h2>
              <p className="text-gray-700 leading-relaxed mb-3">
                You retain ownership of all content you provide to the Service, including:
              </p>
              <ul className="list-disc pl-6 text-gray-700 space-y-2">
                <li>Personal information (name, email, phone, etc.)</li>
                <li>Education and work experience information</li>
                <li>GitHub repository data</li>
                <li>Signature images</li>
              </ul>
              <p className="text-gray-700 leading-relaxed mt-4">
                By using the Service, you grant us a license to use, store, and process your content solely for the 
                purpose of providing the Service. You can delete your account and all associated data at any time 
                through the settings page.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">6. Generated Content</h2>
              <p className="text-gray-700 leading-relaxed">
                All resumes and cover letters generated by the Service are owned by you and can be used freely for 
                any purpose, including job applications. The Service uses AI to generate content, and you are 
                responsible for reviewing and verifying the accuracy of all generated content before use.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">7. Prohibited Uses</h2>
              <p className="text-gray-700 leading-relaxed mb-3">You agree not to use the Service:</p>
              <ul className="list-disc pl-6 text-gray-700 space-y-2">
                <li>For any unlawful purpose or to solicit others to perform unlawful acts</li>
                <li>To violate any international, federal, provincial, or state regulations, rules, laws, or local ordinances</li>
                <li>To infringe upon or violate our intellectual property rights or the intellectual property rights of others</li>
                <li>To harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate</li>
                <li>To submit false or misleading information</li>
                <li>To upload or transmit viruses or any other type of malicious code</li>
                <li>To collect or track the personal information of others</li>
                <li>To spam, phish, pharm, pretext, spider, crawl, or scrape</li>
                <li>For any obscene or immoral purpose</li>
                <li>To interfere with or circumvent the security features of the Service</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">8. Service Availability</h2>
              <p className="text-gray-700 leading-relaxed">
                We strive to provide a reliable service but do not guarantee that the Service will be available at 
                all times. The Service may be unavailable due to maintenance, updates, or unforeseen circumstances. 
                We are not liable for any loss or damage resulting from Service unavailability.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">9. Third-Party Services</h2>
              <p className="text-gray-700 leading-relaxed">
                The Service integrates with third-party services, including GitHub, OpenAI, and Supabase. Your use 
                of these services is subject to their respective terms of service and privacy policies. We are not 
                responsible for the practices of these third-party services.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">10. Disclaimer of Warranties</h2>
              <p className="text-gray-700 leading-relaxed">
                THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS 
                OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
                PARTICULAR PURPOSE, OR NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, 
                SECURE, OR ERROR-FREE.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">11. Limitation of Liability</h2>
              <p className="text-gray-700 leading-relaxed">
                TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, 
                SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED 
                DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING 
                FROM YOUR USE OF THE SERVICE.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">12. Account Termination</h2>
              <p className="text-gray-700 leading-relaxed">
                You may terminate your account at any time by deleting it through the settings page. We reserve 
                the right to suspend or terminate your account if you violate these Terms of Service or engage in 
                any fraudulent, abusive, or illegal activity.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">13. Changes to Terms</h2>
              <p className="text-gray-700 leading-relaxed">
                We reserve the right to modify these Terms of Service at any time. We will notify users of any 
                material changes by posting the updated terms on this page and updating the "Last updated" date. 
                Your continued use of the Service after such changes constitutes acceptance of the new terms.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">14. Governing Law</h2>
              <p className="text-gray-700 leading-relaxed">
                These Terms of Service shall be governed by and construed in accordance with the laws of 
                the State of California, United States, without regard to its conflict of law provisions.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">15. Contact Information</h2>
              <p className="text-gray-700 leading-relaxed">
                If you have any questions about these Terms of Service, please contact us at:
              </p>
              <ul className="list-disc pl-6 text-gray-700 space-y-2 mt-3">
                <li>Email: jacobptnguyen@gmail.com</li>
                <li>GitHub: <a href="https://github.com/jacobptnguyen" className="text-blue-600 hover:underline" target="_blank" rel="noopener noreferrer">jacobptnguyen</a></li>
              </ul>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
};

